server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:38761/eureka/
# db config
spring:
  application:
    name: photoshoot-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/photoshoot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  zipkin:
    base-url: http://localhost:39411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  http:
    converters:
      preferred-json-mapper: fastjson
# redis配置
#  redis:
#    jedis:
#      pool:
#        max-active:
#        max-idle:
#        max-wait:
#        min-idle:
#    timeout:
#    port:
#    password:
#    host:


#logging.你的包名.mybatis接口包=debug
# mybatis


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
#  生成实体类的别名
  type-aliases-package: com.intrantes.entity
  configuration:
#    开启驼峰自动映射
    map-underscore-to-camel-case: true
#    全局映射器启用缓存
    cache-enabled: true
#    查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: false
#    对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
#    允许使用列标签代替列名
    use-column-label: true
#    不允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    use-generated-keys: true
#    给予被嵌套的resultMap以字段-属性的映射支持 FULL,PARTIAL
    auto-mapping-behavior: partial


#cas.server-url-prefix=http
##CAS服务登出地址
#cas.server.host.logout_url=${cas.server.host.url}/logout?service=${app.server.host.url}

cas:
 server:
   host:
    url: http://localhost:8081/cas #cas服务地址
    login_url: ${cas.server.host.url}/login #登录地址
    logout_url: ${cas.server.host.url}/logout #注销地址
app:
  server:
    host:
#      应用访问地址
      url: http://localhost:8080
  login:
#    应用登录地址
    url: /login
  logout:
#    应用登出地址
    url: /logout



logging:
  config: classpath:log/logback.xml
#debug: true
