# db config

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://127.0.0.1:3306/photoshoot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
# mvc配置
  mvc:
    view:
      prefix: /templates/
      suffix: .html
# redis配置
#  redis:
#    jedis:
#      pool:
#        max-active:
#        max-idle:
#        max-wait:
#        min-idle:
#    timeout:
#    port:
#    password:
#    host:


#logging.你的包名.mybatis接口包=debug
# mybatis


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
#  生成实体类的别名
  type-aliases-package: com.intrantes.entity
  configuration:
#    开启驼峰自动映射
    map-underscore-to-camel-case: true
#    全局映射器启用缓存
    cache-enabled: true
#    查询时，关闭关联对象即时加载以提高性能
    lazy-loading-enabled: false
#    对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
#    允许使用列标签代替列名
    use-column-label: true
#    不允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    use-generated-keys: true
#    给予被嵌套的resultMap以字段-属性的映射支持 FULL,PARTIAL
    auto-mapping-behavior: partial
#cas:
# server:
#   host:
#    url: http://192.168.1.101/cas #cas服务地址
#    login_url: /login #登录地址
#    logout_url: /logout #注销地址

#cas.server-url-prefix=http
##CAS服务地址
#cas.server.host.url=http://localhost:8081/cas
##CAS服务登录地址
#cas.server.host.login_url=${cas.server.host.url}/login
##CAS服务登出地址
#cas.server.host.logout_url=${cas.server.host.url}/logout?service=${app.server.host.url}
##应用访问地址
#app.server.host.url=http://localhost:8080
##应用登录地址
#app.login.url=/login
##应用登出地址
#app.logout.url=/logout

logging:
  config: classpath:log/log4j2_dev.xml
